### ISSUE TITLE
Replication follow in prometheus

### ISSUE THREAD

**Issue by ligerard** [PureStorage-OpenConnect/pure-exporter#15]
Hi, I look for a solution to get replication activity on flasharray like on graphical vue. I'd like to put it in prometheus to get alert when we have problem
![image](https://user-images.githubusercontent.com/46193690/76953014-48cbdd00-690e-11ea-984c-4e886341ba73.png)

**Comment by genegr** [comment]
Hi, is that for mirrored write, I guess. In that case there is a specific set of Prometheus metrics:

purefa_mirror_write_latency_usec
purefa_mirror_write_iops
purefa_mirror_write_bytes

so you could define a threshold for the alertmanager on any of those.

**Comment by ligerard** [comment]
Hi ,
  Since you recent update, i use these metrics for active cluster
But  i look disponibility and RPO on asynchronous replication  (snapshots
on a 3rd distance bay)


Le sam. 28 mars 2020 à 19:16, Eugenio Grosso <notifications@github.com> a
écrit :

**Comment by genegr** [comment]
The data that is rendered in the async replication graphs is not available by the REST API, so I am now looking at the possibility to access that through the specific endpoint used by the UI. It shouldn't be a difficult thing, the only problem I could see is the future maintenance of the code because of the lack of a "standard" interface.

**Comment by sdodsley** [comment]
pure-exporter deprecated as noted in README
