### ISSUE TITLE
flashblade exporter: AttributeError: 'ArraysApi' object has no attribute 'list_arrays_nfs_specific_performance'

### ISSUE THREAD

**Issue by isshwar** [PureStorage-OpenConnect/pure-exporter#24]
Hi,

i am trying to set up flashblade exporter and prometheus to scrape the metrics. While setting that up, for /metrics , /metrics/array, /metrics/quota the exporter is failing with the error message
AttributeError: 'ArraysApi' object has no attribute 'list_arrays_nfs_specific_performance' 
whereas for the endpoint /metrics/clients, i don't see this error. 
can you tell me if this is a bug and if yes, can this be fixed?

Thanks
Eswar

**Comment by genegr** [comment]
Hi @isshwar , are you using the dockerized version or directly the Python code? According to your description of the error it seems quite the latter. If that is the case it depends on the 'purity-fb' version that must be >= 1.10. The 'list_arrays_nfs_specific_performance' method has been introduced in that release and is directly related to the array nfs_specific_performance. Could yuo please provide that detail so that I can further investigate whether it is a bug?
Thanks,

**Comment by isshwar** [comment]
Hi genegr,

I have using the dockerized version. My compose file set up below. We are running only flashblade and not flasharray, which is the reason for using the pure-fb-exporter. /metrics/clients is not throwing any error but rest of all metric endpoints available for flashblade(/metrics, /metrics/array, /metrics/quotas in the documentation are failing with the same error. 

version: '3'

services:
  pure-exporter:
    image: quay.io/purestorage/pure-fb-exporter:1.2.0
    restart: always
    networks:
       - prom-backend

networks:
  prom-backend:
    external: true

Let me know if you require any further info.
Thanks.

**Comment by genegr** [comment]
Fixed in release v1.2.2. This error was due to different/missing return values from different Purity REST API versions.
