### ISSUE TITLE
Pure Storage FlashBlade system hardware dashboard health completely broken

### ISSUE THREAD

**Issue by florianmulatz** [PureStorage-OpenConnect/pure-exporter#42]
Shows "No data" or "N/A" on any graph / stat-panel

**Comment by gloacai** [comment]
This looks like this dashboard is a copy and paste of the flash array one. All the metrics it's looking for are flasharray ones (`purefa_` vice `purefb_`).  Digging at it more in current master branch `flashblade_collector/flashblade_metrics/array_hardware_metrics.py` needs a lot of love compared to the flasharray version since most of the metrics this dashboard is looking for isn't being exported yet.

**Comment by gloacai** [comment]
As said above, in general need to rework `flashblade_collector/flashblade_metrics/array_hardware_metrics.py` to expose more metrics.

Testing against Purity//FB3.1.4 (chassis, blades, power supplies, fabric modules) and reading https://purity-fb.readthedocs.io/en/latest/Hardware/
* array name, firmware version, average iops, average IO latency, and average throughput: fixed by swapping from `purefa_*` to `purefb_*`
* average power voltage: There doesn't appear to be a way to query for voltage used so that panel will need to be deleted
* average temperature: All the components have a temperature field in their rest api but their value is `None` for all of them, and looking at the Pure's own management web tool I don't see temperature reported anywhere. Guessing this panel should be deleted for now
* location: delete this panel as the `site` is not a field reported by the pure in any query
* capacity usage: need to change the query to `sum(purefb_array_space_bytes{job=~"$job",instance="$instance",dimension="total_physical"}) / sum(purefb_array_capacity_bytes{job=~"$job",instance="$instance"})`
* data reduction: need to change the query to `sum(purefb_array_space_data_reduction{job=~"$job",instance="$instance"})`
* system events: the `purefb_alerts_total` doesn't exist but it looks like it can be queried https://purity-fb.readthedocs.io/en/latest/AlertsApi/#list_alerts
* nvram*: there is not a hardware component type for nvram for the blade, need to delete these panels
* disk bays: not applicable to a FlashBlade array, should swap to monitoring the `fb` component type instead
* failed SSDs: doesn't see like the API exposes down to that detail
* Controller should be swapped to fabric modules and the sub components are different

**Comment by sdodsley** [comment]
Resolved by #43
